### PR TITLE
First time flow

### PR DESCRIPTION
**Pull request by drewbanin**
verbiage in sample files needs some work....

LMK if you have any thoughts around the opinions codified in these sample configs

cc @jthandy

### CODE REVIEW

**Comment by cmerrick** [comment]
I'm not sure we should create the `~/.dbt` directory like this.  I believe if someone did a `sudo pip install dbt` (once we get the package into pip), that directory would be created with `root`'s permissions, which isn't good.  Plus, I don't really see what value it adds.

Otherwise, I like this.

**Comment by jthandy** [comment]
It was a confusing experience for me as a member of this target audience to find that `~/.dbt` hadn't been created for me. I have definitely had to modify stuff in hidden folders before but never had to make one...it feels like something the setup program always does for stuff I use. However, I agree it shouldn't be owned by `root`. If there isn't some other good / easy way to create this with user privileges I'm fine saying the user has to create it; we just have to document that.

**Comment by cmerrick** [comment]
Documenting it is the better option IMO.  Even if we create the folder, we still need to document how to create the file - so I don't think creating the folder automatically adds a whole lot of value.

**Comment by jthandy** [comment]
@drewbanin I think we decided to kill this, yes? if so, just close out and add comments on the reasoning.

**Comment by drewbanin** [comment]
Killing this -- does not provide any value. I think the docs are out of date too

**Pull request closed without merging**
