### PR TITLE
switch profile on command line

### PR DESCRIPTION
**Pull request by drewbanin**
Users can use the `dbt set-profile [profile]` command to switch between profiles. This configuration is stored in `.dbt.yml` which is added to the gitignore file so it can be customized per-user

```bash
dbt set-profile user # default

dbt set-profile user marketing # merge two configs
```

~/.dbt/profiles.yml
```yml
user:
  outputs:
    redshift:
      ...
  run-target: redshift

marketing:
  outputs:
    marketing_redshift:
      ...
  run-target: marketing_redshift
```

### CODE REVIEW

**Comment by cmerrick** [comment]
The profile system was inspired by lein's, which is documented here: https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md

Some takeaways from that doc:
 - their CLI syntax has a difference between adding a profile to the default set of profiles, versus specifying exactly the profiles you want.  I think this is a useful distinction to draw, and I like their syntax for specifying it.
 - their default profiles are `[:base :system :user :provided :dev]`.  I don't think we need a `:system`, `:provided`, or `:dev` profile yet, but it's worth thinking about whether `:base` is something we'd want to add.

**Comment by cmerrick** [comment]
This looks good otherwise, back to you to consider the above

**Comment by drewbanin** [comment]
@cmerrick I think that's really interesting. In practice, I can't see the benefit of loading > 1 profile by default. Are there any use cases here that you can think of?

I do like the `lein with-profile [profile]` command syntax. I think that manually adding parameters as implemented here (`--profile user`) is probably not how this should work. How do you feel about `dbt with-profile user` creating a `.dbt_config.yml` file in the cwd? It would be gitignored, and `dbt` would check for it on startup.

**Comment by cmerrick** [comment]
I don't think we need to load multiple profiles by default right now.

I don't follow the `.dbt_config.yml` idea - what is that file solving?  The implementation I was thinking about with my first comment was just to support syntax like `--with-profile +test` to mean "I want to load the default profiles AND test" versus `--with-profile test` to mean "I just want to load the test profile"

**Comment by drewbanin** [comment]
@cmerrick when you actually use it, it's super annoying to switch args on the command line every time you `dbt run` or `dbt compile`. The use case here is that a project will be fixed to a single profile and users will seldom switch between profiles within a given project. This information is well suited for the `dbt_project.yml` file; however, user profile names will likely differ within an org.

The above is of course speculative, but I think that when it comes down to it we need some non-versioned way of indicating which profile to load for a given models repo.

**Comment by cmerrick** [comment]
@drewbanin lets discuss in 🍖 👾

**Pull request merged**
